-- =====================================================================
-- FOODMAP MADIUN — DATABASE SETUP (ALL-IN-ONE)
-- =====================================================================
-- Versi    : 2.1 (audited vs codebase)
-- Schema   : Supabase (Postgres 15+) + PostGIS
-- Eksekusi : Copy seluruh file ini ke Supabase SQL Editor → Run
--
-- AUDIT NOTES (vs codebase):
--   1. ✅ Kolom `slug` di tabel `tenants` SUDAH ditambahkan + trigger
--      auto-generate (dipakai oleh src/app/[slug]/page.tsx).
--   2. ✅ WA regex match `normalizeWA()` di src/lib/wa.ts.
--   3. ✅ RPC nearby_tenants signature match useNearbyTenants hook.
--   4. ✅ RLS via app_metadata.role match proxy.ts + admin/layout.tsx.
--
-- STRUKTUR FILE INI:
--   Step 1  — Extensions (PostGIS, uuid-ossp, pg_trgm)
--   Step 2  — Tables (categories, tenants, products) + indexes
--   Step 3  — Triggers (set_updated_at, slug auto-generate)
--   Step 4  — RPC Functions (nearby_tenants, tenants_in_view, is_super_admin)
--   Step 5  — Row Level Security (RLS) policies
--   Step 6  — Grants (anon, authenticated)
--   Step 7  — Seed data (categories + 6 PKL Dimong + menu)
--   Step 8  — Verification queries
--
-- SETELAH RUN FILE INI, jalankan SECARA TERPISAH:
--   - 99_create_super_admin.sql  (untuk set role admin pertama)
-- =====================================================================


-- =====================================================================
-- STEP 1 — EXTENSIONS
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS postgis     WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_trgm     WITH SCHEMA extensions;


-- =====================================================================
-- STEP 2 — TABLES
-- =====================================================================

-- ---------- 2.1 categories ----------

CREATE TABLE IF NOT EXISTS public.categories (
  id          uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  nama        text NOT NULL UNIQUE,
  icon        text,
  urutan      int  NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now()
);


-- ---------- 2.2 tenants ----------

CREATE TABLE IF NOT EXISTS public.tenants (
  id              uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  nama            text NOT NULL,
  slug            text UNIQUE,                            -- auto-generated by trigger
  deskripsi       text,
  foto_url        text,
  foto_public_id  text,
  nomor_wa        text NOT NULL,
  latitude        double precision NOT NULL,
  longitude       double precision NOT NULL,
  location        extensions.geography(POINT, 4326)
                  GENERATED ALWAYS AS (
                    extensions.ST_SetSRID(
                      extensions.ST_MakePoint(longitude, latitude), 4326
                    )::extensions.geography
                  ) STORED,
  alamat          text,
  jam_buka        text,
  hari_libur      text[] DEFAULT ARRAY[]::text[],
  rating          numeric(2,1) CHECK (rating BETWEEN 0 AND 5),
  total_review    int CHECK (total_review >= 0),
  is_active       boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT tenants_lat_check  CHECK (latitude  BETWEEN -90  AND 90),
  CONSTRAINT tenants_lng_check  CHECK (longitude BETWEEN -180 AND 180),
  CONSTRAINT tenants_wa_check   CHECK (nomor_wa ~ '^62[0-9]{8,14}$')
);

CREATE INDEX IF NOT EXISTS idx_tenants_location  ON public.tenants USING GIST (location);
CREATE INDEX IF NOT EXISTS idx_tenants_active    ON public.tenants (is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_tenants_nama_trgm ON public.tenants USING GIN (nama extensions.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_tenants_slug      ON public.tenants (slug);


-- ---------- 2.3 products ----------

CREATE TABLE IF NOT EXISTS public.products (
  id              uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  tenant_id       uuid NOT NULL REFERENCES public.tenants(id)    ON DELETE CASCADE,
  category_id     uuid NOT NULL REFERENCES public.categories(id) ON DELETE RESTRICT,
  nama            text NOT NULL,
  deskripsi       text,
  harga           numeric(10,2) NOT NULL CHECK (harga >= 0),
  foto_url        text,
  foto_public_id  text,
  is_available    boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_products_tenant    ON public.products (tenant_id);
CREATE INDEX IF NOT EXISTS idx_products_category  ON public.products (category_id);
CREATE INDEX IF NOT EXISTS idx_products_available ON public.products (tenant_id, is_available) WHERE is_available = true;


-- =====================================================================
-- STEP 3 — TRIGGERS
-- =====================================================================

-- ---------- 3.1 set_updated_at ----------

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tenants_set_updated_at  ON public.tenants;
CREATE TRIGGER tenants_set_updated_at
  BEFORE UPDATE ON public.tenants
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS products_set_updated_at ON public.products;
CREATE TRIGGER products_set_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ---------- 3.2 slug auto-generate ----------
-- Slugify nama → kebab-case + suffix angka kalau bentrok.
-- Dipakai untuk routing /[slug]/page.tsx (SEO-friendly URL).
--
-- ⚠️ ORDERING: unaccent_safe() HARUS dideklarasi DULUAN sebelum slugify(),
-- karena LANGUAGE sql validate dependency saat CREATE (beda dengan plpgsql
-- yang lazy). Kalau di-swap, akan error "function unaccent_safe does not exist".

-- Fallback unaccent kalau extension unaccent ga aktif.
-- (Kita ga enable unaccent supaya ga nambah dependency — pakai stripper sederhana).
CREATE OR REPLACE FUNCTION public.unaccent_safe(input text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT translate(
           coalesce(input, ''),
           'àáâãäåèéêëìíîïòóôõöùúûüñçÀÁÂÃÄÅÈÉÊËÌÍÎÏÒÓÔÕÖÙÚÛÜÑÇ',
           'aaaaaaeeeeiiiiooooouuuuncAAAAAAEEEEIIIIOOOOOUUUUNC'
         );
$$;

CREATE OR REPLACE FUNCTION public.slugify(input text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT regexp_replace(
           regexp_replace(
             lower(public.unaccent_safe(coalesce(input, ''))),
             '[^a-z0-9]+', '-', 'g'
           ),
           '(^-+|-+$)', '', 'g'
         );
$$;

CREATE OR REPLACE FUNCTION public.tenants_set_slug()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  base_slug   text;
  candidate   text;
  counter     int := 1;
BEGIN
  -- Hanya generate slug kalau:
  --   - INSERT dan slug NULL/empty
  --   - UPDATE dan nama berubah dan slug NULL/empty
  IF (TG_OP = 'INSERT' AND (NEW.slug IS NULL OR NEW.slug = ''))
     OR (TG_OP = 'UPDATE' AND NEW.nama IS DISTINCT FROM OLD.nama
         AND (NEW.slug IS NULL OR NEW.slug = '')) THEN

    base_slug := public.slugify(NEW.nama);
    IF base_slug = '' THEN
      base_slug := 'warung';
    END IF;

    candidate := base_slug;

    -- Loop sampai dapat slug unik
    WHILE EXISTS (
      SELECT 1 FROM public.tenants
      WHERE slug = candidate
        AND (TG_OP = 'INSERT' OR id <> NEW.id)
    ) LOOP
      counter := counter + 1;
      candidate := base_slug || '-' || counter;
    END LOOP;

    NEW.slug := candidate;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tenants_set_slug_trigger ON public.tenants;
CREATE TRIGGER tenants_set_slug_trigger
  BEFORE INSERT OR UPDATE OF nama ON public.tenants
  FOR EACH ROW EXECUTE FUNCTION public.tenants_set_slug();


-- =====================================================================
-- STEP 4 — RPC FUNCTIONS
-- =====================================================================

-- ---------- 4.1 nearby_tenants ----------

CREATE OR REPLACE FUNCTION public.nearby_tenants(
  user_lat   double precision,
  user_lng   double precision,
  radius_km  int DEFAULT 5
)
RETURNS TABLE (
  id            uuid,
  nama          text,
  foto_url      text,
  nomor_wa      text,
  latitude      double precision,
  longitude     double precision,
  alamat        text,
  jam_buka      text,
  rating        numeric,
  dist_meters   double precision
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, extensions
AS $$
  SELECT
    t.id, t.nama, t.foto_url, t.nomor_wa,
    t.latitude, t.longitude, t.alamat, t.jam_buka, t.rating,
    extensions.ST_Distance(
      t.location,
      extensions.ST_SetSRID(extensions.ST_MakePoint(user_lng, user_lat), 4326)::extensions.geography
    ) AS dist_meters
  FROM public.tenants t
  WHERE t.is_active = true
    AND extensions.ST_DWithin(
      t.location,
      extensions.ST_SetSRID(extensions.ST_MakePoint(user_lng, user_lat), 4326)::extensions.geography,
      radius_km * 1000
    )
  ORDER BY t.location <-> extensions.ST_SetSRID(extensions.ST_MakePoint(user_lng, user_lat), 4326)::extensions.geography;
$$;


-- ---------- 4.2 tenants_in_view ----------

CREATE OR REPLACE FUNCTION public.tenants_in_view(
  min_lat   double precision,
  min_lng   double precision,
  max_lat   double precision,
  max_lng   double precision
)
RETURNS TABLE (
  id          uuid,
  nama        text,
  foto_url    text,
  nomor_wa    text,
  latitude    double precision,
  longitude   double precision
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, extensions
AS $$
  SELECT t.id, t.nama, t.foto_url, t.nomor_wa, t.latitude, t.longitude
  FROM public.tenants t
  WHERE t.is_active = true
    AND t.location operator(extensions.&&)
        extensions.ST_SetSRID(
          extensions.ST_MakeBox2D(
            extensions.ST_Point(min_lng, min_lat),
            extensions.ST_Point(max_lng, max_lat)
          ),
          4326
        );
$$;


-- ---------- 4.3 is_super_admin ----------

CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS boolean
LANGUAGE sql STABLE
AS $$
  SELECT COALESCE(
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'super_admin',
    false
  );
$$;


-- =====================================================================
-- STEP 5 — ROW LEVEL SECURITY
-- =====================================================================

ALTER TABLE public.tenants    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;


-- ---------- 5.1 tenants policies ----------

DROP POLICY IF EXISTS "tenants_public_read_active" ON public.tenants;
CREATE POLICY "tenants_public_read_active"
  ON public.tenants FOR SELECT
  TO anon, authenticated
  USING (is_active = true);

DROP POLICY IF EXISTS "tenants_admin_read_all" ON public.tenants;
CREATE POLICY "tenants_admin_read_all"
  ON public.tenants FOR SELECT
  TO authenticated
  USING (public.is_super_admin());

DROP POLICY IF EXISTS "tenants_admin_insert" ON public.tenants;
CREATE POLICY "tenants_admin_insert"
  ON public.tenants FOR INSERT TO authenticated
  WITH CHECK (public.is_super_admin());

DROP POLICY IF EXISTS "tenants_admin_update" ON public.tenants;
CREATE POLICY "tenants_admin_update"
  ON public.tenants FOR UPDATE TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

DROP POLICY IF EXISTS "tenants_admin_delete" ON public.tenants;
CREATE POLICY "tenants_admin_delete"
  ON public.tenants FOR DELETE TO authenticated
  USING (public.is_super_admin());


-- ---------- 5.2 products policies ----------

DROP POLICY IF EXISTS "products_public_read" ON public.products;
CREATE POLICY "products_public_read"
  ON public.products FOR SELECT
  TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.tenants t
      WHERE t.id = products.tenant_id AND t.is_active = true
    )
  );

DROP POLICY IF EXISTS "products_admin_read_all" ON public.products;
CREATE POLICY "products_admin_read_all"
  ON public.products FOR SELECT TO authenticated
  USING (public.is_super_admin());

DROP POLICY IF EXISTS "products_admin_insert" ON public.products;
CREATE POLICY "products_admin_insert"
  ON public.products FOR INSERT TO authenticated
  WITH CHECK (public.is_super_admin());

DROP POLICY IF EXISTS "products_admin_update" ON public.products;
CREATE POLICY "products_admin_update"
  ON public.products FOR UPDATE TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

DROP POLICY IF EXISTS "products_admin_delete" ON public.products;
CREATE POLICY "products_admin_delete"
  ON public.products FOR DELETE TO authenticated
  USING (public.is_super_admin());


-- ---------- 5.3 categories policies ----------

DROP POLICY IF EXISTS "categories_public_read" ON public.categories;
CREATE POLICY "categories_public_read"
  ON public.categories FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "categories_admin_write" ON public.categories;
CREATE POLICY "categories_admin_write"
  ON public.categories FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());


-- =====================================================================
-- STEP 6 — GRANTS
-- =====================================================================

GRANT EXECUTE ON FUNCTION public.nearby_tenants(double precision, double precision, int)
  TO anon, authenticated;

GRANT EXECUTE ON FUNCTION public.tenants_in_view(double precision, double precision, double precision, double precision)
  TO anon, authenticated;

GRANT EXECUTE ON FUNCTION public.is_super_admin()
  TO authenticated;

GRANT EXECUTE ON FUNCTION public.slugify(text)
  TO anon, authenticated;

GRANT EXECUTE ON FUNCTION public.unaccent_safe(text)
  TO anon, authenticated;


-- =====================================================================
-- STEP 7 — SEED DATA
-- =====================================================================

-- ---------- 7.1 categories (idempotent) ----------

INSERT INTO public.categories (nama, icon, urutan) VALUES
  ('Makanan', '🍽️', 1),
  ('Minuman', '🥤', 2)
ON CONFLICT (nama) DO NOTHING;


-- ---------- 7.2 tenants (6 PKL Dimong) ----------
-- WAJIB di-refine via LocationPicker di admin setelah survey lapangan.
-- Koordinat di bawah adalah perkiraan area Desa Dimong, Kec. Madiun.

INSERT INTO public.tenants (
  nama, deskripsi, nomor_wa,
  latitude, longitude, alamat,
  jam_buka, hari_libur,
  rating, total_review, is_active
) VALUES
  (
    'Sate Gule Kambing & Sapi DIMONG',
    'Sate kambing & sapi otentik khas Dimong, gulenya berkuah kental dan rempah pekat.',
    '6285123450001',
    -7.5648, 111.5322,
    'Desa Dimong, Kec. Madiun (patokan: dekat balai desa)',
    '16:00 - 23:00',
    ARRAY[]::text[],
    NULL, NULL, true
  ),
  (
    'Mie Ayam Dan Bakso Manunggaling',
    'Mie ayam yamin + bakso urat porsi mantap. Tempat duduk lesehan & meja.',
    '6285123450002',
    -7.5655, 111.5318,
    'Jl. desa Dimong (patokan: pertigaan menuju Manunggaling)',
    '09:00 - 21:00',
    ARRAY[]::text[],
    NULL, NULL, true
  ),
  (
    'Warung Berkah Soto',
    'Soto ayam kuning bening, nasi pisah atau campur, tambah kerupuk + es teh.',
    '6285123450003',
    -7.5642, 111.5325,
    'Desa Dimong (patokan: depan SD Dimong)',
    '06:00 - 14:00',
    ARRAY['minggu'],
    NULL, NULL, true
  ),
  (
    'Nasi Pecel Bu Rum Ds Dimong',
    'Nasi pecel sambal kacang halus, sayur segar, gorengan pelengkap. Buka subuh.',
    '6285123450004',
    -7.5651, 111.5320,
    'Desa Dimong (patokan: dekat pasar pagi)',
    '05:00 - 11:00',
    ARRAY[]::text[],
    NULL, NULL, true
  ),
  (
    'Sate Gule Bu Marni',
    'Sate kambing muda + gule. Spesialnya bumbu kacang yang bikin nagih.',
    '6285123450005',
    -7.5658, 111.5315,
    'Desa Dimong (patokan: pojok pertigaan Dimong-Manguharjo)',
    '17:00 - 23:00',
    ARRAY['senin'],
    NULL, NULL, true
  ),
  (
    'Roti Bakar Gandaria Dimong',
    'Roti bakar coklat keju, srikaya, selai stroberi. Nongkrong sore-malem ramah kantong.',
    '6285123450006',
    -7.5645, 111.5328,
    'Desa Dimong (patokan: Jl. Gandaria, pinggir jalan utama)',
    '15:00 - 23:00',
    ARRAY[]::text[],
    NULL, NULL, true
  )
ON CONFLICT DO NOTHING;


-- ---------- 7.3 products (menu per warung) ----------

DO $$
DECLARE
  v_tenant_id  uuid;
  v_makanan_id uuid;
  v_minuman_id uuid;
BEGIN
  SELECT id INTO v_makanan_id FROM public.categories WHERE nama = 'Makanan';
  SELECT id INTO v_minuman_id FROM public.categories WHERE nama = 'Minuman';

  -- Skip seed produk kalau sudah ada (idempotent)
  IF (SELECT count(*) FROM public.products) > 0 THEN
    RAISE NOTICE 'Products sudah ada, skip seed produk.';
    RETURN;
  END IF;

  -- 1) Sate Gule Kambing & Sapi DIMONG
  SELECT id INTO v_tenant_id FROM public.tenants WHERE nama = 'Sate Gule Kambing & Sapi DIMONG';
  IF v_tenant_id IS NOT NULL THEN
    INSERT INTO public.products (tenant_id, category_id, nama, deskripsi, harga) VALUES
      (v_tenant_id, v_makanan_id, 'Sate Kambing (10 tusuk)', 'Lemak ideal, bumbu kacang melimpah', 35000),
      (v_tenant_id, v_makanan_id, 'Sate Sapi (10 tusuk)',    'Daging sapi pilihan, empuk',         32000),
      (v_tenant_id, v_makanan_id, 'Gule Kambing',            'Kuah kental, rempah pekat',          25000),
      (v_tenant_id, v_minuman_id, 'Es Teh Manis',            NULL,                                  4000);
  END IF;

  -- 2) Mie Ayam Dan Bakso Manunggaling
  SELECT id INTO v_tenant_id FROM public.tenants WHERE nama = 'Mie Ayam Dan Bakso Manunggaling';
  IF v_tenant_id IS NOT NULL THEN
    INSERT INTO public.products (tenant_id, category_id, nama, deskripsi, harga) VALUES
      (v_tenant_id, v_makanan_id, 'Mie Ayam Yamin',     'Mie kenyal, ayam manis gurih',  12000),
      (v_tenant_id, v_makanan_id, 'Mie Ayam Bakso',     'Mie ayam + bakso urat 3 biji',  17000),
      (v_tenant_id, v_makanan_id, 'Bakso Urat Komplit', 'Bakso urat 5 + tahu + mie',     15000),
      (v_tenant_id, v_minuman_id, 'Es Jeruk',           NULL,                              5000);
  END IF;

  -- 3) Warung Berkah Soto
  SELECT id INTO v_tenant_id FROM public.tenants WHERE nama = 'Warung Berkah Soto';
  IF v_tenant_id IS NOT NULL THEN
    INSERT INTO public.products (tenant_id, category_id, nama, deskripsi, harga) VALUES
      (v_tenant_id, v_makanan_id, 'Soto Ayam Campur',       'Nasi campur dalam mangkok',   13000),
      (v_tenant_id, v_makanan_id, 'Soto Ayam Pisah',        'Nasi pisah dari kuah',        13000),
      (v_tenant_id, v_makanan_id, 'Tambahan Telur Pindang', NULL,                           4000),
      (v_tenant_id, v_minuman_id, 'Es Teh',                 NULL,                           4000);
  END IF;

  -- 4) Nasi Pecel Bu Rum
  SELECT id INTO v_tenant_id FROM public.tenants WHERE nama = 'Nasi Pecel Bu Rum Ds Dimong';
  IF v_tenant_id IS NOT NULL THEN
    INSERT INTO public.products (tenant_id, category_id, nama, deskripsi, harga) VALUES
      (v_tenant_id, v_makanan_id, 'Nasi Pecel Komplit',      'Sayur + sambel + peyek + telur', 12000),
      (v_tenant_id, v_makanan_id, 'Nasi Pecel + Tempe Tahu', 'Plus gorengan',                  10000),
      (v_tenant_id, v_makanan_id, 'Pecel Saja (lauk pisah)', NULL,                              8000),
      (v_tenant_id, v_minuman_id, 'Teh Anget',               NULL,                              3000);
  END IF;

  -- 5) Sate Gule Bu Marni
  SELECT id INTO v_tenant_id FROM public.tenants WHERE nama = 'Sate Gule Bu Marni';
  IF v_tenant_id IS NOT NULL THEN
    INSERT INTO public.products (tenant_id, category_id, nama, deskripsi, harga) VALUES
      (v_tenant_id, v_makanan_id, 'Sate Kambing Muda (10 tusuk)', 'Empuk, ga prengus',     38000),
      (v_tenant_id, v_makanan_id, 'Gule Bu Marni',                'Spesial bumbu kacang',  28000),
      (v_tenant_id, v_makanan_id, 'Tongseng Kambing',             NULL,                    30000),
      (v_tenant_id, v_minuman_id, 'Es Jeruk Peras',               NULL,                     6000);
  END IF;

  -- 6) Roti Bakar Gandaria Dimong
  SELECT id INTO v_tenant_id FROM public.tenants WHERE nama = 'Roti Bakar Gandaria Dimong';
  IF v_tenant_id IS NOT NULL THEN
    INSERT INTO public.products (tenant_id, category_id, nama, deskripsi, harga) VALUES
      (v_tenant_id, v_makanan_id, 'Roti Bakar Coklat Keju',   'Klasik favorit',         15000),
      (v_tenant_id, v_makanan_id, 'Roti Bakar Srikaya',       'Rasa pandan otentik',    14000),
      (v_tenant_id, v_makanan_id, 'Roti Bakar Stroberi Keju', NULL,                     15000),
      (v_tenant_id, v_minuman_id, 'Susu Coklat Hangat',       NULL,                      8000),
      (v_tenant_id, v_minuman_id, 'Teh Tarik',                NULL,                      7000);
  END IF;
END $$;


-- =====================================================================
-- STEP 8 — VERIFICATION
-- =====================================================================
-- Jalankan satu per satu di SQL Editor untuk verifikasi.

-- 1. Cek extensions (expected: 3 rows)
-- SELECT extname FROM pg_extension WHERE extname IN ('postgis', 'pg_trgm', 'uuid-ossp');

-- 2. Cek tabel (expected: 3 rows)
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public' AND table_name IN ('tenants', 'products', 'categories');

-- 3. Cek RLS aktif (expected: rowsecurity = true semua)
-- SELECT tablename, rowsecurity FROM pg_tables
-- WHERE schemaname = 'public' AND tablename IN ('tenants', 'products', 'categories');

-- 4. Cek seed data
-- SELECT count(*) AS tenants_count    FROM public.tenants;       -- expected: 6
-- SELECT count(*) AS categories_count FROM public.categories;    -- expected: 2
-- SELECT count(*) AS products_count   FROM public.products;      -- expected: ~25

-- 5. Cek slug auto-generated
-- SELECT nama, slug FROM public.tenants ORDER BY nama;
-- expected: slug terisi semua, e.g. "sate-gule-kambing-sapi-dimong"

-- 6. Test RPC nearby (expected: 6 rows, dist_meters ascending)
-- SELECT id, nama, dist_meters FROM public.nearby_tenants(-7.5650, 111.5320, 2);

-- 7. Test RPC tenants_in_view (expected: 6 rows)
-- SELECT id, nama FROM public.tenants_in_view(-7.575, 111.525, -7.555, 111.540);


-- =====================================================================
-- DONE — lanjut ke 99_create_super_admin.sql
-- =====================================================================
