/**
 * AUTO-GENERATED STUB.
 *
 * File ini akan di-OVERWRITE oleh:
 *   pnpm types:gen
 *
 * Yang menjalankan:
 *   supabase gen types typescript --project-id YOUR_PROJECT_REF --schema public
 *
 * Stub ini hanya supaya `pnpm build` & TypeScript tidak error sebelum
 * Supabase project di-setup. Tipe lengkap (auto + manual sync dengan schema)
 * keluar setelah types:gen dijalankan.
 *
 * Schema source: 02-DATABASE-SCHEMA.md
 *
 * NOTE: Field `slug` ditambahkan setelah audit roadmap — slug-based routing
 * pakai trigger auto-generate dari `nama` di DB.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          nama: string
          slug: string
          deskripsi: string | null
          foto_url: string | null
          foto_public_id: string | null
          nomor_wa: string
          latitude: number
          longitude: number
          location: unknown // PostGIS geography(POINT, 4326) — di-handle DB
          alamat: string | null
          jam_buka: string | null
          hari_libur: string[]
          rating: number | null
          total_review: number | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          nama: string
          slug?: string // auto-generated by trigger if missing
          deskripsi?: string | null
          foto_url?: string | null
          foto_public_id?: string | null
          nomor_wa: string
          latitude: number
          longitude: number
          alamat?: string | null
          jam_buka?: string | null
          hari_libur?: string[]
          rating?: number | null
          total_review?: number | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          nama?: string
          slug?: string
          deskripsi?: string | null
          foto_url?: string | null
          foto_public_id?: string | null
          nomor_wa?: string
          latitude?: number
          longitude?: number
          alamat?: string | null
          jam_buka?: string | null
          hari_libur?: string[]
          rating?: number | null
          total_review?: number | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }

      products: {
        Row: {
          id: string
          tenant_id: string
          category_id: string
          nama: string
          deskripsi: string | null
          harga: number
          foto_url: string | null
          foto_public_id: string | null
          is_available: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          category_id: string
          nama: string
          deskripsi?: string | null
          harga: number
          foto_url?: string | null
          foto_public_id?: string | null
          is_available?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          category_id?: string
          nama?: string
          deskripsi?: string | null
          harga?: number
          foto_url?: string | null
          foto_public_id?: string | null
          is_available?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_tenant_id_fkey"
            columns: ["tenant_id"]
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            referencedRelation: "categories"
            referencedColumns: ["id"]
          }
        ]
      }

      categories: {
        Row: {
          id: string
          nama: string
          icon: string | null
          urutan: number
          created_at: string
        }
        Insert: {
          id?: string
          nama: string
          icon?: string | null
          urutan?: number
          created_at?: string
        }
        Update: {
          id?: string
          nama?: string
          icon?: string | null
          urutan?: number
          created_at?: string
        }
        Relationships: []
      }
    }

    Views: {
      [_ in never]: never
    }

    Functions: {
      nearby_tenants: {
        Args: {
          user_lat: number
          user_lng: number
          radius_km?: number
        }
        Returns: {
          id: string
          nama: string
          foto_url: string | null
          nomor_wa: string
          latitude: number
          longitude: number
          alamat: string | null
          jam_buka: string | null
          rating: number | null
          dist_meters: number
        }[]
      }

      tenants_in_view: {
        Args: {
          min_lat: number
          min_lng: number
          max_lat: number
          max_lng: number
        }
        Returns: {
          id: string
          nama: string
          foto_url: string | null
          nomor_wa: string
          latitude: number
          longitude: number
        }[]
      }

      is_super_admin: {
        Args: Record<string, never>
        Returns: boolean
      }
    }

    Enums: {
      [_ in never]: never
    }

    CompositeTypes: {
      [_ in never]: never
    }
  }
}